cache:
   pipeline: [~/versions]
   event: [$SD_SOURCE_DIR/node_modules]
   job:
       usejobcache: [/tmp/test]

jobs:
    setnpmcache:
        image: node:14
        steps:
            - install: npm install
        requires: [~commit, ~pr]
    usenpmcache:
        image: node:14
        steps:
            - ls: ls
            - install: npm install
        requires: [setnpmcache]
    usepipelinecache:
        image: java:7
        steps:
            - cat: cat ~/versions || echo "versions file doesn't exist"
            - install: echo "v1.0.0" > ~/versions
        requires: [~commit, ~pr]
    usejobcache:
        image: node:14
        steps:
            - ls-tmp: ls /tmp
            - echo: echo hi > /tmp/test
            - cat: cat ~/versions || echo "versions file doesn't exist"
        requires: [~commit, ~pr]
